export const books = [
  {
    name: "To Kill a Mockingbird",
    slug: "to-kill-a-mockingbird",
    cover: "mockingbird.jpg",
    language: "English",
    downloads: 25000,
    pages: 324,
    type: "Paperback",
    size: "10MB",
    rate: 4.9,
    price: "14.99",
    description: "A classic novel of racism and injustice.",
    authorName: "Harper Lee",
    publisherId: 1,
    categoryName: "Fiction",
  },
  {
    name: "1984",
    slug: "1984",
    cover: "1984.jpg",
    language: "English",
    downloads: 30000,
    pages: 328,
    type: "Hardcover",
    size: "12MB",
    rate: 4.8,
    price: "19.99",
    description: "A dystopian social science fiction novel.",
    authorName: "George Orwell",
    publisherId: 2,
    categoryName: "Dystopian",
  },
  {
    name: "Pride and Prejudice",
    slug: "pride-and-prejudice",
    cover: "pride-prejudice.jpg",
    language: "English",
    downloads: 20000,
    pages: 279,
    type: "eBook",
    size: "8MB",
    rate: 4.7,
    price: "9.99",
    description: "A romantic novel by Jane Austen.",
    authorName: "Jane Austen",
    publisherId: 3,
    categoryName: "Romance",
  },
  {
    name: "The Great Gatsby",
    slug: "the-great-gatsby",
    cover: "gatsby.jpg",
    language: "English",
    downloads: 27000,
    pages: 180,
    type: "Paperback",
    size: "7MB",
    rate: 4.5,
    price: "12.99",
    description: "A story of the Jazz Age in the United States.",
    authorName: "F. Scott Fitzgerald",
    publisherId: 4,
    categoryName: "Classic",
  },
  {
    name: "Moby Dick",
    slug: "moby-dick",
    cover: "moby-dick.jpg",
    language: "English",
    downloads: 15000,
    pages: 635,
    type: "Paperback",
    size: "15MB",
    rate: 4.2,
    price: "18.99",
    description: "The saga of Captain Ahab and the white whale.",
    authorName: "Herman Melville",
    publisherId: 5,
    categoryName: "Adventure",
  },
  {
    name: "War and Peace",
    slug: "war-and-peace",
    cover: "war-peace.jpg",
    language: "English",
    downloads: 20000,
    pages: 1225,
    type: "Hardcover",
    size: "25MB",
    rate: 4.6,
    price: "24.99",
    description: "A historical novel by Leo Tolstoy.",
    authorName: "Leo Tolstoy",
    publisherId: 6,
    categoryName: "Historical",
  },
  {
    name: "The Catcher in the Rye",
    slug: "the-catcher-in-the-rye",
    cover: "catcher-rye.jpg",
    language: "English",
    downloads: 28000,
    pages: 214,
    type: "Paperback",
    size: "6MB",
    rate: 4.3,
    price: "10.99",
    description: "A story about adolescent angst and rebellion.",
    authorName: "J.D. Salinger",
    publisherId: 7,
    categoryName: "Fiction",
  },
  {
    name: "The Hobbit",
    slug: "the-hobbit",
    cover: "hobbit.jpg",
    language: "English",
    downloads: 32000,
    pages: 310,
    type: "eBook",
    size: "9MB",
    rate: 4.8,
    price: "14.99",
    description: "A fantasy novel by J.R.R. Tolkien.",
    authorName: "J.R.R. Tolkien",
    publisherId: 8,
    categoryName: "Fantasy",
  },
  {
    name: "Crime and Punishment",
    slug: "crime-and-punishment",
    cover: "crime-punishment.jpg",
    language: "English",
    downloads: 18000,
    pages: 671,
    type: "Paperback",
    size: "14MB",
    rate: 4.4,
    price: "17.99",
    description: "A novel by Fyodor Dostoevsky.",
    authorName: "Fyodor Dostoevsky",
    publisherId: 9,
    categoryName: "Philosophical",
  },
  {
    name: "Brave New World",
    slug: "brave-new-world",
    cover: "brave-new-world.jpg",
    language: "English",
    downloads: 21000,
    pages: 311,
    type: "Paperback",
    size: "11MB",
    rate: 4.6,
    price: "13.99",
    description: "A dystopian novel by Aldous Huxley.",
    authorName: "Aldous Huxley",
    publisherId: 10,
    categoryName: "Science Fiction",
  },
  {
    name: "Anna Karenina",
    slug: "anna-karenina",
    cover: "anna-karenina.jpg",
    language: "English",
    downloads: 22000,
    pages: 864,
    type: "Hardcover",
    size: "20MB",
    rate: 4.7,
    price: "22.99",
    description: "A novel by Leo Tolstoy.",
    authorName: "Leo Tolstoy",
    publisherId: 6,
    categoryName: "Romance",
  },
  {
    name: "Fahrenheit 451",
    slug: "fahrenheit-451",
    cover: "fahrenheit-451.jpg",
    language: "English",
    downloads: 24000,
    pages: 249,
    type: "eBook",
    size: "8MB",
    rate: 4.5,
    price: "9.99",
    description: "A dystopian novel by Ray Bradbury.",
    authorName: "Ray Bradbury",
    publisherId: 11,
    categoryName: "Dystopian",
  },
  {
    name: "The Grapes of Wrath",
    slug: "the-grapes-of-wrath",
    cover: "grapes-of-wrath.jpg",
    language: "English",
    downloads: 19000,
    pages: 464,
    type: "Paperback",
    size: "13MB",
    rate: 4.4,
    price: "15.99",
    description: "A realist novel by John Steinbeck.",
    authorName: "John Steinbeck",
    publisherId: 12,
    categoryName: "Historical",
  },
  {
    name: "The Odyssey",
    slug: "the-odyssey",
    cover: "odyssey.jpg",
    language: "English",
    downloads: 16000,
    pages: 500,
    type: "Paperback",
    size: "12MB",
    rate: 4.7,
    price: "16.99",
    description: "An ancient Greek epic by Homer.",
    authorName: "Homer",
    publisherId: 13,
    categoryName: "Epic",
  },
  {
    name: "The Lord of the Rings",
    slug: "the-lord-of-the-rings",
    cover: "lotr.jpg",
    language: "English",
    downloads: 50000,
    pages: 1178,
    type: "Hardcover",
    size: "25MB",
    rate: 4.9,
    price: "29.99",
    description: "An epic fantasy novel by J.R.R. Tolkien.",
    authorName: "J.R.R. Tolkien",
    publisherId: 8,
    categoryName: "Fantasy",
  },
  {
    name: "The Iliad",
    slug: "the-iliad",
    cover: "iliad.jpg",
    language: "English",
    downloads: 15000,
    pages: 704,
    type: "Paperback",
    size: "14MB",
    rate: 4.6,
    price: "18.99",
    description: "An ancient Greek epic by Homer.",
    authorName: "Homer",
    publisherId: 13,
    categoryName: "Epic",
  },
  {
    name: "A Tale of Two Cities",
    slug: "a-tale-of-two-cities",
    cover: "tale-two-cities.jpg",
    language: "English",
    downloads: 23000,
    pages: 448,
    type: "Paperback",
    size: "13MB",
    rate: 4.5,
    price: "14.99",
    description: "A novel by Charles Dickens.",
    authorName: "Charles Dickens",
    publisherId: 14,
    categoryName: "Historical",
  },
  {
    name: "Frankenstein",
    slug: "frankenstein",
    cover: "frankenstein.jpg",
    language: "English",
    downloads: 16000,
    pages: 280,
    type: "Paperback",
    size: "9MB",
    rate: 4.4,
    price: "12.99",
    description: "A novel by Mary Shelley.",
    authorName: "Mary Shelley",
    publisherId: 15,
    categoryName: "Science Fiction",
  },
  {
    name: "Dracula",
    slug: "dracula",
    cover: "dracula.jpg",
    language: "English",
    downloads: 17000,
    pages: 418,
    type: "Paperback",
    size: "11MB",
    rate: 4.3,
    price: "13.99",
    description: "A Gothic horror novel by Bram Stoker.",
    authorName: "Bram Stoker",
    publisherId: 16,
    categoryName: "Horror",
  },
  {
    name: "The Alchemist",
    slug: "the-alchemist",
    cover: "the-alchemist.jpg",
    language: "English",
    downloads: 30000,
    pages: 208,
    type: "Paperback",
    size: "6MB",
    rate: 4.8,
    price: "11.99",
    description: "A philosophical novel by Paulo Coelho.",
    authorName: "Paulo Coelho",
    publisherId: 17,
    categoryName: "Philosophical",
  },
  {
    name: "The Da Vinci Code",
    slug: "the-da-vinci-code",
    cover: "da-vinci-code.jpg",
    language: "English",
    downloads: 25000,
    pages: 454,
    type: "Paperback",
    size: "13MB",
    rate: 4.6,
    price: "14.99",
    description: "A mystery thriller novel by Dan Brown.",
    authorName: "Dan Brown",
    publisherId: 18,
    categoryName: "Thriller",
  },
  {
    name: "The Road",
    slug: "the-road",
    cover: "the-road.jpg",
    language: "English",
    downloads: 15000,
    pages: 287,
    type: "Paperback",
    size: "9MB",
    rate: 4.2,
    price: "12.99",
    description: "A post-apocalyptic novel by Cormac McCarthy.",
    authorName: "Cormac McCarthy",
    publisherId: 19,
    categoryName: "Dystopian",
  },
  {
    name: "The Shining",
    slug: "the-shining",
    cover: "the-shining.jpg",
    language: "English",
    downloads: 21000,
    pages: 447,
    type: "Paperback",
    size: "13MB",
    rate: 4.6,
    price: "13.99",
    description: "A horror novel by Stephen King.",
    authorName: "Stephen King",
    publisherId: 20,
    categoryName: "Horror",
  },
  {
    name: "Gone with the Wind",
    slug: "gone-with-the-wind",
    cover: "gone-with-wind.jpg",
    language: "English",
    downloads: 19000,
    pages: 1037,
    type: "Paperback",
    size: "20MB",
    rate: 4.7,
    price: "21.99",
    description: "A historical novel by Margaret Mitchell.",
    authorName: "Margaret Mitchell",
    publisherId: 21,
    categoryName: "Historical",
  },
];
